name: Translation Helper

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

permissions: 
  issues : write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/translation-helper@v1.2.0
